// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/10/2026, 4:58:27 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Personal/Desktop/Proyectos/Repsy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/plugins/**/*.{js,ts,mjs}","C:/Users/Personal/Desktop/Proyectos/Repsy/composables/**/*.{js,ts,mjs}","C:/Users/Personal/Desktop/Proyectos/Repsy/utils/**/*.{js,ts,mjs}","C:/Users/Personal/Desktop/Proyectos/Repsy/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Personal/Desktop/Proyectos/Repsy/app.config.{js,ts,mjs}","C:/Users/Personal/Desktop/Proyectos/Repsy/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;