// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/2/2026, 2:40:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Dario/Desktop/Proyectos/gymApp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/plugins/**/*.{js,ts,mjs}","C:/Users/Dario/Desktop/Proyectos/gymApp/composables/**/*.{js,ts,mjs}","C:/Users/Dario/Desktop/Proyectos/gymApp/utils/**/*.{js,ts,mjs}","C:/Users/Dario/Desktop/Proyectos/gymApp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dario/Desktop/Proyectos/gymApp/app.config.{js,ts,mjs}","C:/Users/Dario/Desktop/Proyectos/gymApp/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;